modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="hbm"
version="${file.jarVersion}"
displayName="Harder Branch Mining Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-branch-mining"
logoFile="HBM-Logo.png"
authors="MacTso, Lupicus"
description='''Harder Branch Mining Mod.'''
[[dependencies.hbm]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hbm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,1.16)"
    ordering="NONE"
    side="BOTH"
